### ISSUE TITLE
BlackmagicRaw Reader

### ISSUE THREAD

**Issue by rodlie** [NatronGitHub/openfx-arena#12]
Requested by William Young.

**Comment by rodlie** [comment]
Initial plugin added. Still need to add support for macOS (might have time to look into that this weekend).

Plugin in action: https://youtu.be/IT-7esMYiss

**Comment by devernay** [comment]
See also https://patchwork.ffmpeg.org/project/ffmpeg/patch/20191214115705.25497-1-onemda@gmail.com/#49278

**Comment by rodlie** [comment]
Does it have the same options? Using the "SDK" we have the same options as in Resolve.

**Comment by devernay** [comment]
No, and it may be not fully working, but at least it's compatible with the GPL (the Blackmagic Raw SDK is closed source, so it's a no-no for distribution with Natron)

**Comment by rodlie** [comment]
But the point of BRAW is all the options, "just" reading the file is not good enough (then I could just use some other format), at least from my POV.

Technically we can include the SDK libs, as we don't link against them, and a GPL software bundle can include proprietary software/programs (see most Linux distros).

> By contrast, pipes, sockets and command-line arguments are communication mechanisms normally used between two separate programs. So when they are used for communication, the modules normally are separate programs.

But, that was not my plan, currently the OFX plugin will search for the installed libraries and use them. The user will need to download and run the BRAW installer from Blackmagic before using the reader in Natron. So no issues there.

Worst case I can maintain binaries outside of Natron.

**Comment by devernay** [comment]
no: GPL doesn't allow any of that.

no linux distribution is GPL, AFAIK.

And closed-source kernel drivers are not authorized by the GPL:
https://www.gnu.org/licenses/gpl-faq.en.html#NonfreeDriverKernelLinux

If you want to dristribute this plugin, you should do it in a non-GPL package, since the proprietary library is required to make the plugin work, which is simply a violation of the license.

I suppose "all the options" are just post-processing, since the data is the same. Let them just provide a utility to convert raw footage into something that can be ingested by other software.

The only way to force Blackmagic into releasing proper open source software is to NOT integrate their "open" library into any open source software. They would be too happy if every open source software integrated their proprietary codec.

They also know that open-source and license-free alternatives to their codec exist, but they're just forcing their customers into using theirs.

**Comment by rodlie** [comment]
plugin moved to https://github.com/rodlie/openfx-braw
